In [1]:
# %load_ext autoreload
# %autoreload 2

import sys
import pathlib

# Ensure the notebook can import the local src package from the project root.
project_root = pathlib.Path.cwd()
if not (project_root / 'src').exists():
    project_root = project_root.parent
sys.path.insert(0, str(project_root.resolve()))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sunpy.net import Fido, attrs as a
import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.io import fits
import sunpy.map


from src.utilities import make_cube

# Dowloading AR's
 Here i going to dowload the folowing AR's witch wilson depresions were already computed with a more sofisticated method ussing hinode telescope

| NOAA | Date | θ [deg] | Spot area [Mm²] | B_av [G] | z_W,div [km] | z_W,press [km] |
| --- | --- | --- | --- | --- | --- | --- |
| 11039 | 2010.01.01 | 29 | 284 | 2471 | 659 | 366 |
| 11041 | 2010.01.26 | 20 | 170 | 2068 | 638 | 305 |
| 11106 | 2010.09.16 | 27 | 195 | 2349 | 636 | 381 |
| 11117 | 2010.10.27 | 25 | 522 | 2093 | 561 | 291 |
| 11117 | 2010.10.28 | 35 | 223 | 2090 | 625 | 313 |
| 11363 | 2011.12.06 | 25 | 1268 | 2287 | 524 | 326 |
| 11536 | 2012.07.31 | 34 | 124 | 2181 | 577 | 346 |

## Locating each AR

`a.Instrument.noaa_indices` only gives the global daily sunspot number — it has no per-region position. To get the position of a specific NOAA AR we query the **HEK** (Heliophysics Event Knowledgebase) for `AR` events filtered by `a.hek.AR.NOAANum`. Each matching record carries the region's helioprojective bounding box (`hpc_bbox`) at that date, which we turn into a `(bottom_left, top_right)` pair for a JSOC cutout request.

Since we now want several continuous days per AR (not a single-day snapshot), `locate_ar_window` (in `src/utilities.py`) queries HEK across the *whole* `N_DAYS` window: it takes the **largest** reported half-width/half-height across all those days (the AR's real size can change noticeably day to day) but anchors the box's **position** at the first day only — position drift across the window is left entirely to `a.jsoc.Cutout(tracking=True)`, which follows solar rotation automatically. This keeps every output frame the same pixel shape (required for `make_cube`'s stacking) while staying large enough to contain the AR for the full window.

In [2]:
active_regions = [
    {'noaa': 11039, 'date': '2010-01-01'},
    {'noaa': 11041, 'date': '2010-01-26'},
    {'noaa': 11106, 'date': '2010-09-16'},
    # 11117's two catalog dates (2010-10-27, 2010-10-28) are one continuous AR passage —
    # a multi-day window anchored at the earlier date already covers the later one, so
    # they're merged into a single entry instead of being processed twice.
    {'noaa': 11117, 'date': '2010-10-27'},
    {'noaa': 11363, 'date': '2011-12-06'},
    {'noaa': 11536, 'date': '2012-07-31'},
]

In [3]:
from src.utilities import locate_ar_window

N_DAYS = 2  # minimum continuous days of data to fetch per AR

for ar in active_regions:
    ar['bl'], ar['tr'], ar['time_start'], ar['time_end'] = locate_ar_window(ar['noaa'], ar['date'], n_days=N_DAYS)
    print(f"NOAA {ar['noaa']} ({ar['date']}): window {ar['time_start']} .. {ar['time_end']}  "
          f"bl={ar['bl'].Tx:.1f},{ar['bl'].Ty:.1f}  tr={ar['tr'].Tx:.1f},{ar['tr'].Ty:.1f}")

NOAA 11039 (2010-01-01): window 2010-01-01 00:00:00 .. 2010-01-02 23:59:59  bl=223.4 arcsec,-451.3 arcsec  tr=396.7 arcsec,-382.8 arcsec
NOAA 11041 (2010-01-26): window 2010-01-26 00:00:00 .. 2010-01-27 23:59:59  bl=-297.7 arcsec,-360.6 arcsec  tr=-71.2 arcsec,-295.2 arcsec
NOAA 11106 (2010-09-16): window 2010-09-16 00:00:00 .. 2010-09-17 23:59:59  bl=-570.3 arcsec,-561.1 arcsec  tr=13.9 arcsec,-303.6 arcsec
NOAA 11117 (2010-10-27): window 2010-10-27 00:00:00 .. 2010-10-28 23:59:59  bl=65.4 arcsec,126.6 arcsec  tr=408.9 arcsec,402.6 arcsec
NOAA 11363 (2011-12-06): window 2011-12-06 00:00:00 .. 2011-12-07 23:59:59  bl=-225.0 arcsec,-511.5 arcsec  tr=510.7 arcsec,-199.3 arcsec
NOAA 11536 (2012-07-31): window 2012-07-31 00:00:00 .. 2012-08-01 23:59:59  bl=-481.2 arcsec,-481.8 arcsec  tr=-284.0 arcsec,-412.0 arcsec


## Downloading tracked cutouts from JSOC

With each AR's `(bottom_left, top_right)` box and full `time_start`/`time_end` window in hand, we reuse `src/scripts.py`'s `download_regions`/`make_cubes` — the same helpers already used for the DS9-defined regions — but driven by the HEK-derived boxes instead. `a.jsoc.Cutout(..., tracking=True)` makes JSOC do the cropping and solar-rotation tracking server-side, so we only ever download the small cutout, not the full 4096x4096 disk.

Each AR gets its own `data/raw/NOAA_<number>_<date>/region_01/` directory. `download_regions` now also **resumes** instead of re-fetching: it checks the timestamps already on disk for a region/series and only requests the missing tail of the window, so re-running this notebook after an interrupted download won't duplicate files or waste JSOC export requests.

**Note:** HMI science data only starts ~2010-05-01, so AR 11039 (2010-01-01) and AR 11041 (2010-01-26) predate it and will return zero results — that's expected, not a bug.

**Data volume:** NOAA 11117 is forced onto `hmi.*_45s` for its *entire* `N_DAYS`-day window (see `series_override` below) because JSOC's `hmi.*_720s` series 500-errors for any query touching 2010-10-26..29 — a JSOC-side gap, not our bug. Native 45s cadence over multiple days is an order of magnitude more data than everyone else's 720s. To keep that in check, `sample_override` applies `a.Sample(360*u.s)` for 11117 — JSOC downsamples **server-side**, so we only ever download every 8th 45s frame (≈360s cadence), roughly matching the other ARs' 720s data volume instead of dwarfing it.

In [4]:
from src.scripts import download_regions, make_cubes

notify_email = 'thomas.quamtum@gmail.com'  # must be a JSOC-registered export email
series_list  = ['hmi.Ic_720s', 'hmi.V_720s', 'hmi.M_720s']

# JSOC's *_720s series 500-errors for any query touching 2010-10-26..29 (a gap/bug in their
# 720s index for that window) even though the underlying 45s data is fine. NOAA 11117's
# whole N_DAYS window falls in/around that gap, so fetch it at 45s cadence instead.
series_override = {
    11117: ['hmi.Ic_45s', 'hmi.V_45s', 'hmi.M_45s'],
}

# 45s cadence over N_DAYS days is far more data than everyone else's 720s — downsample
# NOAA 11117 server-side to ~360s (every 8th 45s frame) to keep its volume comparable.
sample_override = {
    11117: 360 * u.s,
}

In [5]:
dry_run = False

all_summaries = []  # (noaa, date, series, summary) for the consolidated report below

for ar in active_regions:
    region_base = pathlib.Path('../data/raw') / f"NOAA_{ar['noaa']}_{ar['date']}"
    regions_hpc = [(ar['bl'], ar['tr'])]
    ar_series   = series_override.get(ar['noaa'], series_list)
    ar_sample   = sample_override.get(ar['noaa'])

    if dry_run:
        print(f"[dry run] NOAA {ar['noaa']} ({ar['date']}) -> {region_base} "
              f"({ar['time_start']} .. {ar['time_end']}, {ar_series}, sample={ar_sample})")
        continue

    for series in ar_series:
        summary = download_regions(regions_hpc, region_base, ar['time_start'], ar['time_end'],
                                    notify_email, series, sample=ar_sample)
        all_summaries.append((ar['noaa'], ar['date'], series, summary))

# Consolidated pass/fail report — useful after a long multi-AR, multi-day run.
failed = [(noaa, date, series, region, info)
          for noaa, date, series, summary in all_summaries
          for region, info in summary.items() if info['status'] == 'failed']
if failed:
    print("\nFAILED downloads:")
    for noaa, date, series, region, info in failed:
        print(f"  NOAA {noaa} ({date}) region_{region:02d} [{series}]: {info['error']}")
else:
    print("\nNo failures." if all_summaries else "")

Region 01 [hmi.Ic_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11039_2010-01-01/region_01
Region 01 [hmi.V_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11039_2010-01-01/region_01
Region 01 [hmi.M_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11039_2010-01-01/region_01
Region 01 [hmi.Ic_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11041_2010-01-26/region_01
Region 01 [hmi.V_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11041_2010-01-26/region_01
Region 01 [hmi.M_720s]: 0 new frames found


Files Downloaded: 0file [00:00, ?file/s]

  -> 0 files saved to ../data/raw/NOAA_11041_2010-01-26/region_01
Region 01 [hmi.Ic_720s]: 120 new frames found (resuming)


2026-08-06 15:40:06 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=2]
2026-08-06 15:40:06 - drms - INFO: Waiting for 5 seconds...
2026-08-06 15:40:12 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=1]
2026-08-06 15:40:12 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:40:22 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=1]
2026-08-06 15:40:22 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:40:32 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=1]
2026-08-06 15:40:32 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:40:43 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=1]
2026-08-06 15:40:43 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:40:53 - drms - INFO: Export request pending. [id=JSOC_20260806_010975, status=1]
2026-08-06 15:40:53 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:41:03 - drms - INFO: Export request pending. [id=JS

INFO: 113 URLs found for download. Full request totaling 89MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/113 [00:00<?, ?file/s]

hmi.ic_720s.20100917_001200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_002400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_003600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_004800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_010000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_011200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_012400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_013600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_014800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_020000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_021200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_022400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_023600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_024800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_030000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_031200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_032400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_033600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_034800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_040000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_041200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_042400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_043600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_044800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_050000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_051200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_052400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_053600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_054800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_060000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_061200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_074800_TAI.1.continuum.fits:   0%|          | 0.00/786k [00:00<?, ?B/s]

hmi.ic_720s.20100917_080000_TAI.1.continuum.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.ic_720s.20100917_081200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_082400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_083600_TAI.1.continuum.fits:   0%|          | 0.00/835k [00:00<?, ?B/s]

hmi.ic_720s.20100917_084800_TAI.1.continuum.fits:   0%|          | 0.00/835k [00:00<?, ?B/s]

hmi.ic_720s.20100917_090000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_091200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_092400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_093600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_094800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_100000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_101200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_102400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_103600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_104800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_110000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_111200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_112400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_113600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_114800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_120000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_121200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_122400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_123600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_124800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_130000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_131200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_132400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_133600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_134800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_140000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_141200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_142400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_143600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_144800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_150000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_151200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_152400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_153600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_154800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_160000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_161200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_162400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_163600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_164800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_170000_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_171200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_172400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_173600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_174800_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_180000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_181200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_182400_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_183600_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_184800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_190000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_191200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_192400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_193600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_194800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_200000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_201200_TAI.1.continuum.fits:   0%|          | 0.00/832k [00:00<?, ?B/s]

hmi.ic_720s.20100917_202400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_203600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_204800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_210000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_211200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_212400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_213600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_214800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_220000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_221200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_222400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_223600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_224800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_230000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_231200_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_232400_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_233600_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100917_234800_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

hmi.ic_720s.20100918_000000_TAI.1.continuum.fits:   0%|          | 0.00/829k [00:00<?, ?B/s]

  -> 113 files saved to ../data/raw/NOAA_11106_2010-09-16/region_01
Region 01 [hmi.V_720s]: 120 new frames found (resuming)


2026-08-06 15:43:07 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=2]
2026-08-06 15:43:07 - drms - INFO: Waiting for 5 seconds...
2026-08-06 15:43:13 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=1]
2026-08-06 15:43:13 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:43:23 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=1]
2026-08-06 15:43:23 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:43:33 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=1]
2026-08-06 15:43:33 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:43:44 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=1]
2026-08-06 15:43:44 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:43:54 - drms - INFO: Export request pending. [id=JSOC_20260806_011008, status=1]
2026-08-06 15:43:54 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:44:04 - drms - INFO: Export request pending. [id=JS

INFO: 113 URLs found for download. Full request totaling 88MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/113 [00:00<?, ?file/s]

hmi.v_720s.20100917_001200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_002400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_003600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_004800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_010000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_011200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_012400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_013600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_014800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_020000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_021200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_022400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_023600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_024800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_030000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_031200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_032400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_033600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_034800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_040000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_041200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_042400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_043600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_044800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_050000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

Exception ignored while calling deallocator <function BaseEventLoop.__del__ at 0x7fdfec0ca770>:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/base_events.py", line 760, in __del__
    self.close()
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/unix_events.py", line 74, in close
    self.remove_signal_handler(sig)
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/unix_events.py", line 163, in remove_signal_handler
    signal.signal(sig, handler)
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/signal.py", line 58, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter


hmi.v_720s.20100917_051200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_052400_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_053600_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_054800_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_060000_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_061200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_074800_TAI.1.Dopplergram.fits:   0%|          | 0.00/775k [00:00<?, ?B/s]

hmi.v_720s.20100917_080000_TAI.1.Dopplergram.fits:   0%|          | 0.00/812k [00:00<?, ?B/s]

hmi.v_720s.20100917_081200_TAI.1.Dopplergram.fits:   0%|          | 0.00/818k [00:00<?, ?B/s]

hmi.v_720s.20100917_082400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_083600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_084800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_090000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_091200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_092400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_093600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_094800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_100000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_101200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_102400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_103600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_104800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_110000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_111200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_112400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_113600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_114800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_120000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_121200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_122400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_123600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_124800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_130000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_131200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_132400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_133600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_134800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_140000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_141200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_142400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_143600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_144800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_150000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_151200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_152400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_153600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_154800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_160000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_161200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_162400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_163600_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_164800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_170000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_171200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_172400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_173600_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_174800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_180000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_181200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_182400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_183600_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_184800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_190000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_191200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_192400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_193600_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_194800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_200000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_201200_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_202400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_203600_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_204800_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_210000_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_211200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_212400_TAI.1.Dopplergram.fits:   0%|          | 0.00/821k [00:00<?, ?B/s]

hmi.v_720s.20100917_213600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_214800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_220000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_221200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_222400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_223600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_224800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_230000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_231200_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_232400_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_233600_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100917_234800_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

hmi.v_720s.20100918_000000_TAI.1.Dopplergram.fits:   0%|          | 0.00/824k [00:00<?, ?B/s]

  -> 113 files saved to ../data/raw/NOAA_11106_2010-09-16/region_01
Region 01 [hmi.M_720s]: 120 new frames found (resuming)


2026-08-06 15:46:20 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=2]
2026-08-06 15:46:20 - drms - INFO: Waiting for 5 seconds...
2026-08-06 15:46:26 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=1]
2026-08-06 15:46:26 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:46:36 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=1]
2026-08-06 15:46:36 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:46:47 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=1]
2026-08-06 15:46:47 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:46:57 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=1]
2026-08-06 15:46:57 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:47:07 - drms - INFO: Export request pending. [id=JSOC_20260806_011041, status=1]
2026-08-06 15:47:07 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:47:17 - drms - INFO: Export request pending. [id=JS

INFO: 113 URLs found for download. Full request totaling 74MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/113 [00:00<?, ?file/s]

hmi.m_720s.20100917_001200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_002400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_003600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_004800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_010000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_011200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_012400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_013600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_014800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_020000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_021200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_022400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_023600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_024800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_030000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_031200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_032400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_033600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_034800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_040000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_041200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_042400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_043600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_044800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_050000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_051200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_052400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_053600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_054800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_060000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_061200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_074800_TAI.1.magnetogram.fits:   0%|          | 0.00/668k [00:00<?, ?B/s]

hmi.m_720s.20100917_081200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_082400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_083600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_084800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_090000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_091200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_092400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_093600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_094800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_100000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_101200_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_102400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_103600_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_104800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_110000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_111200_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_112400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_113600_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_114800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_120000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_121200_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_122400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_123600_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_124800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_130000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_131200_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_132400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_133600_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_134800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_140000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_141200_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_142400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_143600_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_144800_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_150000_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_151200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_152400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_153600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_154800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_160000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_161200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_162400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_163600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_164800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_170000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_171200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_172400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_173600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_174800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_180000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_181200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_182400_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_183600_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_184800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_190000_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_191200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_192400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_193600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_194800_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_200000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_201200_TAI.1.magnetogram.fits:   0%|          | 0.00/683k [00:00<?, ?B/s]

hmi.m_720s.20100917_202400_TAI.1.magnetogram.fits:   0%|          | 0.00/685k [00:00<?, ?B/s]

hmi.m_720s.20100917_203600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_204800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_210000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_211200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_212400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_213600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_214800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_220000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_221200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_222400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_223600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_224800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_230000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_231200_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_232400_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_233600_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100917_234800_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

hmi.m_720s.20100918_000000_TAI.1.magnetogram.fits:   0%|          | 0.00/680k [00:00<?, ?B/s]

2026-08-06 15:53:56 - parfive - INFO: http://jsoc.stanford.edu/SUM14/D2024267263/S00000/hmi.m_720s.20100917_080000_TAI.1.magnetogram.fits failed to download with exception
Timeout on reading data from socket
2026-08-06 15:53:56 - parfive - INFO: http://jsoc.stanford.edu/SUM14/D2024267263/S00000/hmi.m_720s.20100917_110000_TAI.1.magnetogram.fits failed to download with exception
Timeout on reading data from socket
2026-08-06 15:53:56 - parfive - INFO: http://jsoc.stanford.edu/SUM14/D2024267263/S00000/hmi.m_720s.20100917_190000_TAI.1.magnetogram.fits failed to download with exception
Timeout on reading data from socket


3/0 files failed to download. Please check `.errors` for details
  -> 110 files saved to ../data/raw/NOAA_11106_2010-09-16/region_01
Region 01 [hmi.Ic_45s]: 240 new frames found (resuming)


2026-08-06 15:54:14 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=2]
2026-08-06 15:54:14 - drms - INFO: Waiting for 5 seconds...
2026-08-06 15:54:20 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=1]
2026-08-06 15:54:20 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:54:30 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=1]
2026-08-06 15:54:30 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:54:40 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=1]
2026-08-06 15:54:40 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:54:51 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=1]
2026-08-06 15:54:51 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:55:01 - drms - INFO: Export request pending. [id=JSOC_20260806_011120, status=1]
2026-08-06 15:55:01 - drms - INFO: Waiting for 10 seconds...
2026-08-06 15:55:11 - drms - INFO: Export request pending. [id=JS

INFO: 230 URLs found for download. Full request totaling 120MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/230 [00:00<?, ?file/s]

hmi.ic_45s.20101028_000215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_000815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_001415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_002015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_002615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_003215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_003815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_004415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_005015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_005615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_010215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_010815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_011415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_012015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_012615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_013215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_013815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_014415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_015015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_015615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_020215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_020815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_021415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_022015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_022615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_023215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_023815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_024415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_025015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_025615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_030215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_030815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_031415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_032015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_032615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_033215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_033815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_034415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_035015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_035615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_040215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_040815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_041415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_042015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_042615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_043215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_043815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_044415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_045015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_045615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_050215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_050815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_051415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_052015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_052615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_053215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_053815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_054415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_055015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_055615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_060215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_060815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_061415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_062015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_062615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_063215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_063815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_064415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_065015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_065615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_070215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_070815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_071415_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_072015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_072615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_073215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_073815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_074415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_075015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_075615_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_080215_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_080815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_081415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_082015_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_082615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_083215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_083815_TAI.2.continuum.fits:   0%|          | 0.00/550k [00:00<?, ?B/s]

hmi.ic_45s.20101028_084415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_085015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_085615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_090215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_090815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_091415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_092015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_092615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_093215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_093815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_094415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_095015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_095615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_100215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_100815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_101415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_102015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_102615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_103215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_103815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_104415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_105015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_105615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_110215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_110815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_111415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_112015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_112615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_113215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_113815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_114415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_115015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_115615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_120215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_120815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_121415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_122015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_122615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_123215_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_123815_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_124415_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_125015_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_125615_TAI.2.continuum.fits:   0%|          | 0.00/547k [00:00<?, ?B/s]

hmi.ic_45s.20101028_130215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_130815_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_131415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_132015_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_132615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_133215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_133815_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_134415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_135015_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_135615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_140215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_140815_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_141415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_142015_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_142615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_143215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_143815_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_144415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_145015_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_145615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_151415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_152615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_153815_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_154415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_160215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_161415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_163215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_164415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_165015_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_165615_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_170215_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_170815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_171415_TAI.2.continuum.fits:   0%|          | 0.00/544k [00:00<?, ?B/s]

hmi.ic_45s.20101028_172015_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_172615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_173215_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_173815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_174415_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_175015_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_175615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_180215_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_180815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_181415_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_182015_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_182615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_183215_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_183815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_184415_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_185015_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_185615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_190215_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_190815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_191415_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_192015_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_192615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_193215_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_193815_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_194415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_195015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_195615_TAI.2.continuum.fits:   0%|          | 0.00/541k [00:00<?, ?B/s]

hmi.ic_45s.20101028_200215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_200815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_201415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_202015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_202615_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_203215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_203815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_204415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_205015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_205615_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_210215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_210815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_211415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_212015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_212615_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_213215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_213815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_214415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_215015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_215615_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_220215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_220815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_221415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_222015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_222615_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_223215_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_223815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_224415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_225015_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_225615_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_230215_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_230815_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_231415_TAI.2.continuum.fits:   0%|          | 0.00/539k [00:00<?, ?B/s]

hmi.ic_45s.20101028_232015_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_232615_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_233215_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_233815_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_234415_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_235015_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

hmi.ic_45s.20101028_235615_TAI.2.continuum.fits:   0%|          | 0.00/536k [00:00<?, ?B/s]

2026-08-06 15:59:59 - parfive - INFO: http://jsoc.stanford.edu/SUM8/D2024268427/S00000/hmi.ic_45s.20101028_053815_TAI.2.continuum.fits failed to download with exception
Cannot connect to host jsoc1.stanford.edu:443 ssl:default [None]


1/0 files failed to download. Please check `.errors` for details
  -> 229 files saved to ../data/raw/NOAA_11117_2010-10-27/region_01
Region 01 [hmi.V_45s]: 240 new frames found (resuming)


2026-08-06 16:00:19 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=2]
2026-08-06 16:00:19 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:00:25 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=1]
2026-08-06 16:00:25 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:00:35 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=1]
2026-08-06 16:00:35 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:00:45 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=1]
2026-08-06 16:00:45 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:00:56 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=1]
2026-08-06 16:00:56 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:01:06 - drms - INFO: Export request pending. [id=JSOC_20260806_011188, status=1]
2026-08-06 16:01:06 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:01:16 - drms - INFO: Export request pending. [id=JS

INFO: 230 URLs found for download. Full request totaling 122MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/230 [00:00<?, ?file/s]

hmi.v_45s.20101028_000215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_000815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_001415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_002015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_002615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_003215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_003815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_004415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_005015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_005615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_010215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_010815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_011415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_012015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_012615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_013215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_013815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_014415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_015015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_015615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_020215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_020815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_021415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_022015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_022615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_023215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_023815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_024415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_025015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_025615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_030215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_030815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_031415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_032015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_032615_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_033215_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_033815_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_034415_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_035015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_035615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_040215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_040815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_041415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_042015_TAI.2.Dopplergram.fits:   0%|          | 0.00/553k [00:00<?, ?B/s]

hmi.v_45s.20101028_042615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_043215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_043815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_044415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_045015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_045615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_050215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_050815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_051415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_052015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_052615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_053215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_053815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_054415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_055015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_055615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_060215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_060815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_061415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_062015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_062615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_063215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_063815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_064415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_065015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_065615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_070215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_070815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_071415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_072015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_072615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_073215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_073815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_074415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_075015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_075615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_080215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_080815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_081415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_082015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_082615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_083215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_083815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_084415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_085015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_085615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_090215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_090815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_091415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_092015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_092615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_093215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_093815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_094415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_095015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_095615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_100215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_100815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_101415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_102015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_102615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_103215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_103815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_104415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_105015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_105615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_110215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_110815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_111415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_112015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_112615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_113215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_113815_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_114415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_115015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_115615_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_120215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_120815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_121415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_122015_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_122615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_123215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_123815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_124415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_125015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_125615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_130215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_130815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_131415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_132015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_132615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_133215_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_133815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_134415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_135015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_135615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_140215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_140815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_141415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_142015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_142615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_143215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_143815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_144415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_145015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_145615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_151415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_152615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_153815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_154415_TAI.2.Dopplergram.fits:   0%|          | 0.00/556k [00:00<?, ?B/s]

hmi.v_45s.20101028_160215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_161415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_163215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_164415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_165015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_165615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_170215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_170815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_171415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_172015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_172615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_173215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_173815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_174415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_175015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_175615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_180215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_180815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_181415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_182015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_182615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_183215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_183815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_184415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_185015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_185615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_190215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_190815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_191415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_192015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_192615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_193215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_193815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_194415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_195015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_195615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_200215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_200815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_201415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_202015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_202615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_203215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_203815_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_204415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_205015_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_205615_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_210215_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_210815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_211415_TAI.2.Dopplergram.fits:   0%|          | 0.00/559k [00:00<?, ?B/s]

hmi.v_45s.20101028_212015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_212615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_213215_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_213815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_214415_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_215015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_215615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_220215_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_220815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_221415_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_222015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_222615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_223215_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_223815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_224415_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_225015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_225615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_230215_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_230815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_231415_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_232015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_232615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_233215_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_233815_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_234415_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_235015_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

hmi.v_45s.20101028_235615_TAI.2.Dopplergram.fits:   0%|          | 0.00/562k [00:00<?, ?B/s]

  -> 230 files saved to ../data/raw/NOAA_11117_2010-10-27/region_01
Region 01 [hmi.M_45s]: 240 new frames found (resuming)


2026-08-06 16:05:21 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=2]
2026-08-06 16:05:21 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:05:27 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=1]
2026-08-06 16:05:27 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:05:37 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=1]
2026-08-06 16:05:37 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:05:47 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=1]
2026-08-06 16:05:47 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:05:57 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=1]
2026-08-06 16:05:57 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:06:08 - drms - INFO: Export request pending. [id=JSOC_20260806_011240, status=1]
2026-08-06 16:06:08 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:06:18 - drms - INFO: Export request pending. [id=JS

INFO: 230 URLs found for download. Full request totaling 104MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/230 [00:00<?, ?file/s]

hmi.m_45s.20101028_000215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_000815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_001415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_002015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_002615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_003215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_003815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_004415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_005015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_005615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_010215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_010815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_011415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_012015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_012615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_013215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_013815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_014415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_015015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_015615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_020215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_020815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_021415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_022015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_022615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_023215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_023815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_024415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_025015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_025615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_030215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_030815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_031415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_032015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_032615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_033215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_033815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_034415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_035015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_035615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_040215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_040815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_041415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_042015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_042615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_043215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_043815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_044415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_045015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_045615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_050215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_050815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_051415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_052015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_052615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_053215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_053815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_054415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_055015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_055615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_060215_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_060815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_061415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_062015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_062615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_063215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_063815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_064415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_065015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_065615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_070215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_070815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_071415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_072015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_072615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_073215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_073815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_074415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_075015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_075615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_080215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_080815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_081415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_082015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_082615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_083215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_083815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_084415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_085015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_085615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_090215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_090815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_091415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_092015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_092615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_093215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_093815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_094415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_095015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_095615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_100215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_100815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_101415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_102015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_102615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_103215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_103815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_104415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_105015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_105615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_110215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_110815_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_111415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_112015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_112615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_113215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_113815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_114415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_115015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_115615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_120215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_120815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_121415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_122015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_122615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_123215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_123815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_124415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_125015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_125615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_130215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_130815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_131415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_132015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_132615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_133215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_133815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_134415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_135015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_135615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_140215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_140815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_141415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_142015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_142615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_143215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_143815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_144415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_145015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_145615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_151415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_152615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_153815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_154415_TAI.2.magnetogram.fits:   0%|          | 0.00/490k [00:00<?, ?B/s]

hmi.m_45s.20101028_160215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_161415_TAI.2.magnetogram.fits:   0%|          | 0.00/469k [00:00<?, ?B/s]

hmi.m_45s.20101028_163215_TAI.2.magnetogram.fits:   0%|          | 0.00/481k [00:00<?, ?B/s]

hmi.m_45s.20101028_164415_TAI.2.magnetogram.fits:   0%|          | 0.00/469k [00:00<?, ?B/s]

hmi.m_45s.20101028_165015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_165615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_170215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_170815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_171415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_172015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_172615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_173215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_173815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_174415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_175015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_175615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_180215_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_180815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_181415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_182015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_182615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_183215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_183815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_184415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_185015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_185615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_190215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_190815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_191415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_192015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_192615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_193215_TAI.2.magnetogram.fits:   0%|          | 0.00/469k [00:00<?, ?B/s]

hmi.m_45s.20101028_193815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_194415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_195015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_195615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_200215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_200815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_201415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_202015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_202615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_203215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_203815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_204415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_205015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_205615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_210215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_210815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_211415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_212015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_212615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_213215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_213815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_214415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_215015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_215615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_220215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_220815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_221415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_222015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_222615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_223215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_223815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_224415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_225015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_225615_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_230215_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_230815_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_231415_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_232015_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_232615_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_233215_TAI.2.magnetogram.fits:   0%|          | 0.00/472k [00:00<?, ?B/s]

hmi.m_45s.20101028_233815_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_234415_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_235015_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

hmi.m_45s.20101028_235615_TAI.2.magnetogram.fits:   0%|          | 0.00/475k [00:00<?, ?B/s]

  -> 230 files saved to ../data/raw/NOAA_11117_2010-10-27/region_01
Region 01 [hmi.Ic_720s]: 120 new frames found (resuming)


2026-08-06 16:10:04 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=2]
2026-08-06 16:10:04 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:10:10 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=1]
2026-08-06 16:10:10 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:10:20 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=1]
2026-08-06 16:10:20 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:10:30 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=1]
2026-08-06 16:10:30 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:10:41 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=1]
2026-08-06 16:10:41 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:10:51 - drms - INFO: Export request pending. [id=JSOC_20260806_011285, status=1]
2026-08-06 16:10:51 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:11:01 - drms - INFO: Export request pending. [id=JS

INFO: 118 URLs found for download. Full request totaling 137MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/118 [00:00<?, ?file/s]

hmi.ic_720s.20111207_001200_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_002400_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_003600_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_004800_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_010000_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_011200_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_012400_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_013600_TAI.1.continuum.fits:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

hmi.ic_720s.20111207_014800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_020000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_021200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_022400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_023600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_024800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_030000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_031200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_032400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_033600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_034800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_040000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_041200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_042400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_043600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_044800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_050000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_051200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_052400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_053600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_054800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_060000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_061200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_062400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_063600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_064800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_070000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_071200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_072400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_073600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_074800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_080000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_081200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_082400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_083600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_084800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_090000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_091200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_092400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_093600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_094800_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_100000_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_101200_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_102400_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_103600_TAI.1.continuum.fits:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

hmi.ic_720s.20111207_104800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_110000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_111200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_112400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_113600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_114800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_120000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_121200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_122400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_123600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_124800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_130000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_131200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_132400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_133600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_134800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_140000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_141200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_142400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_143600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_144800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_150000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_151200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_152400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_153600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_154800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_160000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_161200_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_162400_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_163600_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_164800_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_170000_TAI.1.continuum.fits:   0%|          | 0.00/1.22M [00:00<?, ?B/s]

hmi.ic_720s.20111207_171200_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_172400_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_173600_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_174800_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_180000_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_183600_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_184800_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_190000_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_191200_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_192400_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_193600_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_194800_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_200000_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_201200_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_202400_TAI.1.continuum.fits:   0%|          | 0.00/1.21M [00:00<?, ?B/s]

hmi.ic_720s.20111207_203600_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_204800_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_210000_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_211200_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_212400_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_213600_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_214800_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_220000_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_221200_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_222400_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_223600_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_224800_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_230000_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_231200_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_232400_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_233600_TAI.1.continuum.fits:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

hmi.ic_720s.20111207_234800_TAI.1.continuum.fits:   0%|          | 0.00/1.19M [00:00<?, ?B/s]

hmi.ic_720s.20111208_000000_TAI.1.continuum.fits:   0%|          | 0.00/1.19M [00:00<?, ?B/s]

  -> 118 files saved to ../data/raw/NOAA_11363_2011-12-06/region_01
Region 01 [hmi.V_720s]: 120 new frames found (resuming)


2026-08-06 16:13:43 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=2]
2026-08-06 16:13:43 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:13:48 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=1]
2026-08-06 16:13:48 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:13:58 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=1]
2026-08-06 16:13:58 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:14:08 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=1]
2026-08-06 16:14:08 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:14:19 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=1]
2026-08-06 16:14:19 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:14:29 - drms - INFO: Export request pending. [id=JSOC_20260806_011322, status=1]
2026-08-06 16:14:29 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:14:39 - drms - INFO: Export request pending. [id=JS

INFO: 118 URLs found for download. Full request totaling 143MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/118 [00:00<?, ?file/s]

hmi.v_720s.20111207_001200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_002400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_003600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_004800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_010000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_011200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_012400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_013600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_014800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_020000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_021200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_022400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_023600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_024800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_030000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_031200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

hmi.v_720s.20111207_032400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_033600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_034800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_040000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_041200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_042400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_043600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_044800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_050000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_051200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_052400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_053600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_054800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_060000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_061200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_062400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_063600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_064800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_070000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_071200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_072400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_073600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_074800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_080000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_081200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_082400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_083600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_084800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_090000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_091200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_092400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_093600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_094800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_100000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_101200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_102400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_103600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_104800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_110000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_111200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_112400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_113600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_114800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_120000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_121200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_122400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_123600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_124800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_130000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_131200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_132400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_133600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_134800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_140000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_141200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_142400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_143600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_144800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_150000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_151200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_152400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_153600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_154800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_160000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_161200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_162400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_163600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_164800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_170000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_171200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_172400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_173600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_174800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_180000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_183600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_184800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

hmi.v_720s.20111207_190000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_191200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_192400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_193600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_194800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_200000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_201200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_202400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_203600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_204800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_210000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_211200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_212400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_213600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_214800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_220000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_221200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_222400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_223600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_224800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_230000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_231200_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_232400_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_233600_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111207_234800_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

hmi.v_720s.20111208_000000_TAI.1.Dopplergram.fits:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

  -> 118 files saved to ../data/raw/NOAA_11363_2011-12-06/region_01
Region 01 [hmi.M_720s]: 120 new frames found (resuming)


2026-08-06 16:16:38 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=2]
2026-08-06 16:16:38 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:16:43 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=1]
2026-08-06 16:16:43 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:16:54 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=1]
2026-08-06 16:16:54 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:17:04 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=1]
2026-08-06 16:17:04 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:17:14 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=1]
2026-08-06 16:17:14 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:17:25 - drms - INFO: Export request pending. [id=JSOC_20260806_011351, status=1]
2026-08-06 16:17:25 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:17:35 - drms - INFO: Export request pending. [id=JS

INFO: 118 URLs found for download. Full request totaling 115MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/118 [00:00<?, ?file/s]

hmi.m_720s.20111207_001200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_002400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_003600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_004800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_010000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_011200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_012400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_013600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_014800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_020000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_021200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_022400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_023600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_024800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_030000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_031200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_032400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_033600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_034800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_040000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_041200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_042400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_043600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_044800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_050000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_051200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_052400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_053600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_054800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_060000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_061200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_062400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_063600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_064800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_070000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_071200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_072400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_073600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_074800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_080000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_081200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_082400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_083600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_084800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_090000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_091200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_092400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_093600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_094800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_100000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_101200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_102400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_103600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_104800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_110000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_111200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_112400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_113600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_114800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_120000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_121200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_122400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_123600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_124800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_130000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_131200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_132400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_133600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_134800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_140000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_141200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_142400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_143600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_144800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_150000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_151200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_152400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_153600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_154800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_160000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_161200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_162400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_163600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_164800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_170000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_171200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_172400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_173600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_174800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_180000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_183600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_184800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_190000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_191200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_192400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_193600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_194800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_200000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

hmi.m_720s.20111207_201200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_202400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_203600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_204800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_210000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_211200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_212400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_213600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_214800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_220000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_221200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_222400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_223600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_224800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_230000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_231200_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_232400_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_233600_TAI.1.magnetogram.fits:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

hmi.m_720s.20111207_234800_TAI.1.magnetogram.fits:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

hmi.m_720s.20111208_000000_TAI.1.magnetogram.fits:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

  -> 118 files saved to ../data/raw/NOAA_11363_2011-12-06/region_01
Region 01 [hmi.Ic_720s]: 120 new frames found (resuming)


2026-08-06 16:20:10 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=2]
2026-08-06 16:20:10 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:20:16 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=1]
2026-08-06 16:20:16 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:20:26 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=1]
2026-08-06 16:20:26 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:20:36 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=1]
2026-08-06 16:20:36 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:20:47 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=1]
2026-08-06 16:20:47 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:20:57 - drms - INFO: Export request pending. [id=JSOC_20260806_011388, status=1]
2026-08-06 16:20:57 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:21:08 - drms - INFO: Export request pending. [id=JS

INFO: 120 URLs found for download. Full request totaling 10MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/120 [00:00<?, ?file/s]

hmi.ic_720s.20120801_001200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_002400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_003600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_004800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_010000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_011200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_012400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_013600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_014800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_020000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_021200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_022400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_023600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_024800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_030000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_031200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_032400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_033600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_034800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_040000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_041200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_042400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_043600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_044800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_050000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_051200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_052400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_053600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_054800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_060000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_061200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_062400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_063600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_064800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_070000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_071200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_072400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_073600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_074800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_080000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_081200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_082400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_083600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_084800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_090000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_091200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_092400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_093600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_094800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_100000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_101200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_102400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_103600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_104800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_110000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_111200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_112400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_113600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_114800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_120000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_121200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_122400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_123600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_124800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_130000_TAI.1.continuum.fits:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

hmi.ic_720s.20120801_131200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_132400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_133600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_134800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_140000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_141200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_142400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_143600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_144800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_150000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_151200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_152400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_153600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_154800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_160000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_161200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_162400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_163600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_164800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_170000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_171200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_172400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_173600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_174800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_180000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_181200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_182400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_183600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_184800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_190000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_191200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_192400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_193600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_194800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_200000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_201200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_202400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_203600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_204800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_210000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_211200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_212400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_213600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_214800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_220000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_221200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_222400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_223600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_224800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_230000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_231200_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_232400_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_233600_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120801_234800_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.ic_720s.20120802_000000_TAI.1.continuum.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

  -> 120 files saved to ../data/raw/NOAA_11536_2012-07-31/region_01
Region 01 [hmi.V_720s]: 120 new frames found (resuming)


2026-08-06 16:23:23 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=2]
2026-08-06 16:23:23 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:23:29 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=1]
2026-08-06 16:23:29 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:23:39 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=1]
2026-08-06 16:23:39 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:23:49 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=1]
2026-08-06 16:23:49 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:23:59 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=1]
2026-08-06 16:23:59 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:24:10 - drms - INFO: Export request pending. [id=JSOC_20260806_011425, status=1]
2026-08-06 16:24:10 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:24:20 - drms - INFO: Export request pending. [id=JS

INFO: 120 URLs found for download. Full request totaling 10MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/120 [00:00<?, ?file/s]

hmi.v_720s.20120801_001200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_002400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_003600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_004800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_010000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_011200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_012400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_013600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_014800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_020000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_021200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_022400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_023600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_024800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_030000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_031200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_032400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_033600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_034800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_040000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_041200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_042400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_043600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_044800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_050000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_051200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_052400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_053600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_054800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_060000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_061200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_062400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_063600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_064800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_070000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_071200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_072400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_073600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_074800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_080000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_081200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_082400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_083600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_084800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_090000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_091200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_092400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_093600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_094800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_100000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_101200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_102400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_103600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_104800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_110000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_111200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_112400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_113600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_114800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_120000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_121200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_122400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_123600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_124800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_130000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_131200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_132400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_133600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_134800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_140000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_141200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_142400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_143600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_144800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_150000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_151200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

Exception ignored while calling deallocator <function BaseEventLoop.__del__ at 0x7fdfec0ca770>:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/base_events.py", line 760, in __del__
    self.close()
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/unix_events.py", line 74, in close
    self.remove_signal_handler(sig)
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/unix_events.py", line 163, in remove_signal_handler
    signal.signal(sig, handler)
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/signal.py", line 58, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
Exception ignored while calling deallocator <function BaseEventLoop.__del__ at 0x7fdfec0ca770>:
Traceback (most recent call last):
  File "/home/thomas/.conda/envs/sun-spots/lib/python3.14/asyncio/base_events.py", line 760, in

hmi.v_720s.20120801_152400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_153600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_154800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_160000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_161200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_162400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_163600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_164800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_170000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_171200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_172400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_173600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_174800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_180000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_181200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_182400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_183600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_184800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_190000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_191200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_192400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_193600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_194800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_200000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_201200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_202400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_203600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_204800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_210000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_211200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_212400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_213600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_214800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_220000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_221200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_222400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_223600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_224800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_230000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_231200_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_232400_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_233600_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120801_234800_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

hmi.v_720s.20120802_000000_TAI.1.Dopplergram.fits:   0%|          | 0.00/89.3k [00:00<?, ?B/s]

  -> 120 files saved to ../data/raw/NOAA_11536_2012-07-31/region_01
Region 01 [hmi.M_720s]: 120 new frames found (resuming)


2026-08-06 16:26:17 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=2]
2026-08-06 16:26:17 - drms - INFO: Waiting for 5 seconds...
2026-08-06 16:26:22 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=1]
2026-08-06 16:26:22 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:26:33 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=1]
2026-08-06 16:26:33 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:26:43 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=1]
2026-08-06 16:26:43 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:26:53 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=1]
2026-08-06 16:26:53 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:27:03 - drms - INFO: Export request pending. [id=JSOC_20260806_011458, status=1]
2026-08-06 16:27:03 - drms - INFO: Waiting for 10 seconds...
2026-08-06 16:27:14 - drms - INFO: Export request pending. [id=JS

INFO: 120 URLs found for download. Full request totaling 10MB [sunpy.net.jsoc.jsoc]


Files Downloaded:   0%|          | 0/120 [00:00<?, ?file/s]

hmi.m_720s.20120801_001200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_002400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_003600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_004800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_010000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_011200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_012400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_013600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_014800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_020000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_021200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_022400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_023600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_024800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_030000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_031200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_032400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_033600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_034800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_040000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_041200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_042400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_043600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_044800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_050000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_051200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_052400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_053600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_054800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_060000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_061200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_062400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_063600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_064800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_070000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_071200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_072400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_073600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_074800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_080000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_081200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_082400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_083600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_084800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_090000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_091200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_092400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_093600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_094800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_100000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_101200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_102400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_103600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_104800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_110000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_111200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_112400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_113600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_114800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_120000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_121200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_122400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_123600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_124800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_130000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_131200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_132400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_133600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_134800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_140000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_141200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_142400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_143600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_144800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_150000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_151200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_152400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_153600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_154800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_160000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_161200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_162400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_163600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_164800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_170000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_171200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_172400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_173600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_174800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_180000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_181200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_182400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_183600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_184800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_190000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_191200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_192400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_193600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_194800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_200000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_201200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_202400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_203600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_204800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_210000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_211200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_212400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_213600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_214800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_220000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_221200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_222400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_223600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_224800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_230000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_231200_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_232400_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_233600_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120801_234800_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

hmi.m_720s.20120802_000000_TAI.1.magnetogram.fits:   0%|          | 0.00/86.4k [00:00<?, ?B/s]

  -> 120 files saved to ../data/raw/NOAA_11536_2012-07-31/region_01

No failures.


In [6]:
# 11039/11041 predate HMI science data (starts ~2010-05-01) — genuinely no data to fetch.
# 11117 is kept: it's handled via series_override (45s instead of the broken 720s window).
exclude_noaa = [11039, 11041]
active_regions = [ar for ar in active_regions if ar['noaa'] not in exclude_noaa]

In [7]:
ar = active_regions[2]  
region_base = pathlib.Path('../data/raw') / f"NOAA_{ar['noaa']}_{ar['date']}"
regions_hpc = [(ar['bl'], ar['tr'])]
for series in series_override.get(ar['noaa'], series_list):
    make_cubes(regions_hpc, region_base, series)

2026-08-06 16:30:00 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/179 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.ic_720s.*.continuum.fits)


2026-08-06 16:31:21 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/179 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.v_720s.*.fits)


2026-08-06 16:32:38 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 60/178 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.m_720s.*.magnetogram.fits)


In [8]:
if True:
    for ar in active_regions:
        region_base = pathlib.Path('../data/raw') / f"NOAA_{ar['noaa']}_{ar['date']}"
        regions_hpc = [(ar['bl'], ar['tr'])]
        for series in series_override.get(ar['noaa'], series_list):
            make_cubes(regions_hpc, region_base, series)

2026-08-06 16:33:29 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 60/173 mismatched-shape frame(s) onto the majority (511, 1159) grid (../data/raw/NOAA_11106_2010-09-16/region_01/hmi.ic_720s.*.continuum.fits)


2026-08-06 16:34:23 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/174 mismatched-shape frame(s) onto the majority (511, 1159) grid (../data/raw/NOAA_11106_2010-09-16/region_01/hmi.v_720s.*.fits)


2026-08-06 16:35:20 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/171 mismatched-shape frame(s) onto the majority (511, 1159) grid (../data/raw/NOAA_11106_2010-09-16/region_01/hmi.m_720s.*.magnetogram.fits)


2026-08-06 16:36:12 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 81/418 mismatched-shape frame(s) onto the majority (548, 682) grid (../data/raw/NOAA_11117_2010-10-27/region_01/hmi.ic_45s.*.continuum.fits)


2026-08-06 16:37:02 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 81/419 mismatched-shape frame(s) onto the majority (548, 682) grid (../data/raw/NOAA_11117_2010-10-27/region_01/hmi.v_45s.*.fits)


2026-08-06 16:37:55 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 81/419 mismatched-shape frame(s) onto the majority (548, 682) grid (../data/raw/NOAA_11117_2010-10-27/region_01/hmi.m_45s.*.magnetogram.fits)


2026-08-06 16:39:08 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/179 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.ic_720s.*.continuum.fits)


2026-08-06 16:40:20 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 61/179 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.v_720s.*.fits)


2026-08-06 16:41:28 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.


make_cube: reprojected 60/178 mismatched-shape frame(s) onto the majority (620, 1459) grid (../data/raw/NOAA_11363_2011-12-06/region_01/hmi.m_720s.*.magnetogram.fits)


2026-08-06 16:41:30 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
2026-08-06 16:41:32 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
2026-08-06 16:41:35 - astropy - WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
